require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),morgan=require('morgan');
const connectDB=require('./config/db'),errorHandler=require('./middleware/errorHandler');
connectDB();
const app=express();
const allowedOrigins = process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',') : ['http://localhost:3000','http://localhost:5173'];
app.use(helmet());app.use(cors({origin:allowedOrigins,credentials:true}));app.use(morgan('dev'));
app.use(express.json({limit:'10mb'}));app.use(express.urlencoded({extended:true}));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/dashboard',require('./routes/dashboard'));
app.use('/api/orders',require('./routes/orders'));
app.use('/api/products',require('./routes/products'));
app.use('/api/users',require('./routes/users'));
app.use('/api/notifications',require('./routes/notifications'));
app.get('/api/health',(req,res)=>res.json({status:'ok',timestamp:new Date().toISOString()}));
app.use(errorHandler);
app.listen(process.env.PORT||5000,()=>console.log('Server on port '+(process.env.PORT||5000)));