require('dotenv').config({path:require('path').join(__dirname,'..','.env')});
const mongoose=require('mongoose'),bcrypt=require('bcryptjs'),User=require('../models/User'),Order=require('../models/Order'),Product=require('../models/Product'),Notification=require('../models/Notification'),connectDB=require('../config/db');
connectDB();
const seed=async()=>{try{await User.deleteMany({});await Order.deleteMany({});try{await Product.collection.drop()}catch(e){}await Notification.deleteMany({});
const ap='admin123',up='password123';
const admin=await User.create({name:'John Doe',email:'admin@apex.io',password:ap,role:'admin',avatar:'https://picsum.photos/seed/admin-avatar/80/80.jpg'});
const ud=[{name:'Sarah Wilson',email:'sarah@example.com',avatar:'https://picsum.photos/seed/user1/80/80.jpg'},{name:'Mike Johnson',email:'mike@example.com',avatar:'https://picsum.photos/seed/user2/80/80.jpg'},{name:'Emily Chen',email:'emily@example.com',avatar:'https://picsum.photos/seed/user3/80/80.jpg'},{name:'David Kim',email:'david@example.com',avatar:'https://picsum.photos/seed/user4/80/80.jpg'},{name:'Lisa Anderson',email:'lisa@example.com',avatar:'https://picsum.photos/seed/user5/80/80.jpg'},{name:'James Brown',email:'james@example.com',avatar:'https://picsum.photos/seed/user6/80/80.jpg'},{name:'Anna Taylor',email:'anna@example.com',avatar:'https://picsum.photos/seed/user7/80/80.jpg'},{name:'Robert Martinez',email:'robert@example.com',avatar:'https://picsum.photos/seed/user8/80/80.jpg'},{name:'Sophia Lee',email:'sophia@example.com',avatar:'https://picsum.photos/seed/user9/80/80.jpg'},{name:'William Clark',email:'william@example.com',avatar:'https://picsum.photos/seed/user10/80/80.jpg'}];
const users=await User.create(ud.map(u=>({...u,password:up,role:'user'})));
await User.updateOne({email:'emily@example.com'}, {status:'inactive'});
const pd=[{name:'MacBook Pro 16"',category:'electronics',price:2499,stock:45,totalSold:234,rating:4.8,reviewCount:89,sku:'MBP-16',thumbnail:'https://picsum.photos/seed/product1/80/80.jpg'},{name:'iPhone 15 Pro Max',category:'electronics',price:1199,stock:120,totalSold:567,rating:4.7,reviewCount:234,sku:'IP15-PM',thumbnail:'https://picsum.photos/seed/product2/80/80.jpg'},{name:'Nike Air Max 90',category:'sports',price:129,stock:200,totalSold:890,rating:4.5,reviewCount:156,sku:'NKE-AM90',thumbnail:'https://picsum.photos/seed/product3/80/80.jpg'},{name:'Sony WH-1000XM5',category:'electronics',price:349,stock:8,totalSold:345,rating:4.9,reviewCount:201,sku:'SNY-WH1K',thumbnail:'https://picsum.photos/seed/product4/80/80.jpg'},{name:'AirPods Pro 2',category:'electronics',price:249,stock:5,totalSold:678,rating:4.6,reviewCount:312,sku:'APL-APP2',thumbnail:'https://picsum.photos/seed/product5/80/80.jpg'},{name:'iPad Air M2',category:'electronics',price:799,stock:67,totalSold:189,rating:4.7,reviewCount:98,sku:'IPA-M2',thumbnail:'https://picsum.photos/seed/product6/80/80.jpg'},{name:'Apple Watch Ultra 2',category:'electronics',price:799,stock:34,totalSold:156,rating:4.8,reviewCount:67,sku:'AWU2',thumbnail:'https://picsum.photos/seed/product7/80/80.jpg'},{name:'Cotton Shirt',category:'clothing',price:49,stock:300,totalSold:456,rating:4.3,reviewCount:78,sku:'CLT-SH',thumbnail:'https://picsum.photos/seed/product8/80/80.jpg'},{name:'Denim Jacket',category:'clothing',price:89,stock:150,totalSold:234,rating:4.4,reviewCount:56,sku:'DNM-JK',thumbnail:'https://picsum.photos/seed/product9/80/80.jpg'},{name:'Garden Tool Set',category:'home_garden',price:65,stock:80,totalSold:123,rating:4.2,reviewCount:34,sku:'GRD-TLS',thumbnail:'https://picsum.photos/seed/product10/80/80.jpg'},{name:'Yoga Mat',category:'sports',price:45,stock:200,totalSold:567,rating:4.6,reviewCount:145,sku:'YGA-MT',thumbnail:'https://picsum.photos/seed/product11/80/80.jpg'},{name:'LED Desk Lamp',category:'home_garden',price:39,stock:110,totalSold:289,rating:4.4,reviewCount:87,sku:'LED-DL',thumbnail:'https://picsum.photos/seed/product12/80/80.jpg'}];
const products=await Product.create(pd);
const statuses=['pending','processing','shipped','delivered','completed','cancelled'],weights=[10,15,15,20,35,5];
const wStatus=()=>{const t=weights.reduce((a,b)=>a+b,0);let r=Math.random()*t;for(let i=0;i<statuses.length;i++){r-=weights[i];if(r<=0)return statuses[i]}return 'completed'};
const cities=['New York','Los Angeles','Chicago','Houston','Phoenix'];const orders=[];
for(let i=0;i<200;i++){const u=users[Math.floor(Math.random()*users.length)];const np=Math.floor(Math.random()*3)+1;const ops=[];const used=new Set();
for(let j=0;j<np;j++){let pi;do{pi=Math.floor(Math.random()*products.length)}while(used.has(pi));used.add(pi);const pr=products[pi];ops.push({product:pr._id,name:pr.name,quantity:Math.floor(Math.random()*3)+1,price:pr.price})}
const ta=ops.reduce((s,x)=>s+x.quantity*x.price,0);const da=new Date();da.setDate(da.getDate()-Math.floor(Math.random()*90));
orders.push({orderId:'ORD-'+String(7822-i).padStart(4,'0'),customer:u._id,customerName:u.name,customerEmail:u.email,customerAvatar:u.avatar,products:ops,totalAmount:ta,status:wStatus(),paymentStatus:Math.random()>0.1?'paid':'pending',paymentMethod:['credit_card','paypal','stripe'][Math.floor(Math.random()*3)],createdAt:da,shippingAddress:{street:Math.floor(Math.random()*9999+1)+' Main St',city:cities[Math.floor(Math.random()*5)],state:'NY',zip:String(Math.floor(Math.random()*90000)+10000),country:'US'}})}
await Order.insertMany(orders);
await Notification.create([{user:admin._id,title:'New order',message:'Order #ORD-7821 placed by Sarah Wilson',type:'order',icon:'lucide:shopping-cart',color:'green'},{user:admin._id,title:'Low stock',message:'AirPods Pro 2 running low (5 left)',type:'stock',icon:'lucide:alert-triangle',color:'red'},{user:admin._id,title:'New message',message:'Message from Emily Chen',type:'message',icon:'lucide:message-circle',color:'blue'},{user:admin._id,title:'New user',message:'Mike Johnson registered',type:'user',icon:'lucide:user-plus',color:'blue'},{user:admin._id,title:'5-star review',message:'MacBook Pro 16 got 5 stars',type:'review',icon:'lucide:star',color:'amber'},{user:admin._id,title:'Order shipped',message:'Order #ORD-7819 shipped',type:'order',icon:'lucide:package',color:'violet'},{user:admin._id,title:'Payment received',message:'$2,499 for order #ORD-7821',type:'payment',icon:'lucide:credit-card',color:'green'},{user:admin._id,title:'Update available',message:'Dashboard v2.1 available',type:'system',icon:'lucide:info',color:'blue'}]);
console.log('Done! Admin: admin@apex.io / admin123');process.exit(0)}catch(e){console.error(e);process.exit(1)}};
seed();